webapp/account/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, request
from webapp import db, bcrypt
from webapp.account.utils import save_image, save_profile_image
from webapp.account.form import AccountChangeForm, RegistrationForm, LoginForm
from webapp.models import User, Post, Image
from flask_login import login_user, current_user, logout_user, login_required


account = Blueprint('account', __name__)


@account.route("/user", methods=["GET", "POST"])
def user():
    return render_template('user.html')

@account.route("/login", methods=["GET", "POST"])
def login():  
    form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=False)
            next_page = request.args.get('next')
            flash('login successful', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('login unsuccessful either email or password were incorrect', 'danger')
    return render_template('login.html', form=form)

@account.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@account.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'accounted created for {form.username.data}', 'success')
        return redirect(url_for('main.home'))
    return render_template('register.html', form=form)

@login_required
@account.route("/account_setting", methods=["GET", "POST"])
def account_setting():
    form=AccountChangeForm()
    form.username.data = current_user.username
    form.email.data = current_user.email
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.profile_image = save_profile_image(form.profile_image.data)
        db.session.commit()
        redirect(url_for('main.home'))
    return render_template('account_setting.html', user=current_user, form=form)

@account.route('/user_posts/<int:user_id>')
def user_posts(user_id):
    user = User.query.filter_by(id=user_id).first()
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(user_id=user.id).\
        order_by(Post.time.desc()).\
        paginate(page=page, per_page=5)

    return render_template('user_posts.html', posts=posts, user=user, Image=Image)


@account.route('/profile/<int:user_id>')
def profile(user_id):
    user = User.query.filter_by(id=user_id).first()
    


    return render_template('profile.html', user=user)

@account.route('/user_files/<int:user_id>')
def user_files(user_id):

    return render_template('user_files.html')


@login_required
@account.route('/follow/<int:user_id>')
def follow(user_id):
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        flash('error no such user exist')
        return redirect(url_for('main.home'))
    if current_user.is_following(user):
        flash('already following')
        return redirect(url_for('account.profile', user_id=user.id))

    flash('followed')
    current_user.follow(user)
    return redirect(url_for('account.profile', user_id=user.id))


@login_required
@account.route('/unfollow/<int:user_id>')
def unfollow(user_id):
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        flash('error no such user exist')
        return redirect(url_for('main.home'))
    if not current_user.is_following(user):
        flash('already not following')
        return redirect(url_for('account.profile', user_id=user.id))
    flash('unfollowed')
    current_user.unfollow(user)
    return redirect(url_for('account.profile', user_id=user.id))

@login_required
@account.route('/following/<int:user_id>')
def following(user_id):




    
    return render_template('following.html')



@account.route("/users_list", methods=["GET", "POST"])
def user_list():
    users = User.query.order_by(User.id)
    return render_template('users_list.html', users=users)

webapp/post/routes.py
from flask import Blueprint, render_template, current_app, redirect, url_for, flash, Flask, Request
from flask_login import current_user
from webapp.post.form import PostForm, ImageTestForm
from webapp.models import Post, Image
from webapp import db
from werkzeug.utils import secure_filename
from werkzeug.datastructures import FileStorage
import os

from webapp.post.utils import save_image

post = Blueprint('post', __name__)

@post.route("/create_post", methods=['GET', 'POST'])
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        individual_post=Post(title=form.title.data, text=form.text.data, author=current_user)
        db.session.add(individual_post)
        db.session.commit()
        try:
            for image in form.image.data:
                file_name = secure_filename(save_image(image))
                img = Image(image=file_name, post=individual_post)
                db.session.add(img)
                db.session.commit()
        except:
            pass
        return redirect(url_for('main.home'))
    return render_template('create_post.html', form=form)

@post.route("/update_post", methods=['GET', 'POST'])
def update_post(post_id):
    form = form
    post = Post.query.get_or_404(post_id)
    files_filenames = []

    return render_template('update_post.html', form=form)

@post.route("/post/<int:post_id>")
def single_post(post_id):
    post = Post.query.get_or_404(post_id)
    images = Image.query.filter_by(post=post)
    return render_template('post.html', post=post, images=images)



@post.route('/images_test', methods=['GET', 'POST'])
def image_test():
    form = ImageTestForm()
    individual_post = Post.query.get_or_404(1)
    if form.validate_on_submit():
         for image in form.image.data:
            file_name = secure_filename(image)
            img = Image(image=file_name, post=individual_post)
            db.session.add(img)
            db.session.commit()
    images = Image.query.order_by(Image.id)
    return render_template('image_test.html', form=form, images=images)

@post.route('/ck_editor_test', methods=['GET', 'POST'])
def ck_editor_test():
    form = PostForm()
    if form.validate_on_submit():
        individual_post=Post(title=form.title.data, text=form.text.data, author=current_user)
        db.session.add(individual_post)
        db.session.commit()
        try:
            for image in form.image.data:
                file_name = secure_filename(save_image(image))
                img = Image(image=file_name, post=individual_post)
                db.session.add(img)
                db.session.commit()
        except:
            pass
        return redirect(url_for('main.home'))

    return render_template('ck_editor_test.html', form=form)

webapp/templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
    {{field.label(**kwargs)|safe}}
    {% if field.errors %}
            {{ field(class="form-control form-control-lg is-invalid") |safe }}
            <div class="invalid-feedback">
                {% for error in field.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% else %}
            {{ field(class="form-control form-control-lg") }}
        {% endif %}
</div>
{% endmacro %}

{% macro render_button(button) %}
<div class="form-group">
    {{button(class="btn btn-outline-info")}}
</div>
{% endmacro %}

{% macro render_remember(remember) %}
<div class="form-check">
    {{ remember(class="form-check-input") }}
    {{ remember.label(class="form-check-label") }}
</div>    
{% endmacro %}

webapp/templates/_templatehelpers.html
{% macro render_items() %}
    
{% endmacro %}

webapp/templates/about.html
{% extends 'base.html' %}

{% block body %}
<h1>About</h1>
<div class="d-flex align-items-top">
    <div class="flex-shrink-0">
        <img src="{{ url_for('static', filename='profile_images/main_image2.png') }}" class="" alt="..." style="width:200px">
    </div>
    <div class="flex-grow-1 ms-3">
        I am Jacob Hua, a Sac State Graduate with a BS in Computer Science. Currently I am trying to broaden my skills by creating and
        hosting a blog site.
    </div>
    
</div>

<p>
    This is WIP blog site that I am creating in Flask. Currently implementation of login, registration have been added.
    Future implementations will include UI redesigns, more dynamic posting, and the ability to upload and download files.
    Other features will include follow and friend system to be able easily categorize friends/followed post.
    Other possible implementations will include a web scraping functionality and more. 
</p>

{% endblock %}

webapp/templates/account.html
{% extends 'base.html' %}

{% block body %}
{% endblock %}

webapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="{{ url_for('static', filename='node_modules/bootstrap/dist/css/bootstrap.css') }}" 
    rel="stylesheet" 
    crossorigin="anonymous">
    <script src="{{ url_for('static', filename='node_modules/bootstrap/dist/js/bootstrap.bundle.js') }}" 
    crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{url_for('main.home')}}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
        aria-expanded="false" aria-label="Toggle navigation">

          <span class="navbar-toggler-icon"></span>

        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('account.profile', user_id=current_user.id)}}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('post.create_post')}}">Create Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('account.logout')}}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('account.login')}}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('account.register')}}">Register</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
</head>



<body>

  <div class="container-sm" style="max-width:80%;">
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          {{message}}
        </div>  
      {% endfor %}
    {% endif %}
  {% endwith %}

  {% block body %} 
  {% endblock %}

  </div>




</body>
</html>

webapp/templates/create_post.html
{% extends 'base.html' %}
{% from "_formhelpers.html" import render_field, render_button, render_remember %}

{% block body %}
<form method="POST" enctype="multipart/form-data" action="">
    {{form.hidden_tag()}}
    <fieldset class="form-group">
        <div class="d-grid gap-1">
        {{render_field(form.title)}}
        {{render_field(form.text)}}
        {{form.image(class="form")}}
        {% if form.image.errors %}
                {% for error in form.image.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
        {% endif %}
        {{render_button(form.submit)}}
        </div>
    </fieldset>
</form>
{% endblock %}

webapp/templates/home.html
{% extends 'base.html' %}

{% block body %}
<div class="d-grid gap-3 mt-3 ml-3">
    {% for post in posts.items %}
        <div class="p-2 bg-light border shadow">
            <div class="d-flex gap-1">
                <div class="d-flex flex-column align-items-center">
                    <a href="#">
                    <img class="p-0 rounded-circle" 
                    src="{{url_for('static', filename='profile_images_preview/' + post.author.profile_image)}}" 
                    style="width: 75px; height: 75px;">
                    </a>
                    <a class="p-0" href="{{url_for('account.profile', user_id = post.author.id)}}">{{ post.author.username }}</a>

                </div>
                <div class="flex-grow-1 vh-10">
                    <h2><a href="{{url_for('post.single_post', post_id = post.id)}}" style="color:inherit; text-decoration: none;">{{post.title}}</a></h2>
                    <div class="border overflow-auto" style="white-space: pre-line; height: 200px;">{{post.text}}</div>
                    {% for image in Image.query.filter_by(post=post) %}
                    <img src="{{url_for('static', filename='images_preview/' + image.image)}}" alt="" width="125px">
                    {% endfor %}
                </div>
            </div>     
        </div>
    {% endfor %}


    <div class="">
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        
        {% if page_num %}
            {% if page_num == posts.page %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num)}}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num)}}">{{ page_num }}</a>
            {% endif%} 
        {% else %}
        ...
        {% endif%}
        
        {% endfor %}
    </div>

</div>


{% endblock %}

webapp/templates/login.html
{% extends 'base.html' %}
{% from "_formhelpers.html" import render_field, render_button, render_remember %}

{% block body %}
    <div class="container-sm" style="max-width: 600px;">
        <form method="POST" action="">
            {{form.hidden_tag()}}
            <fieldset class="form-group">
                <div class="d-grid gap-1">
                    <legend class="border-bottom me-4">Login</legend>
                    {{render_field(form.email)}}
                    {{render_field(form.password)}}
                    {{render_button(form.submit)}}
                </div>
            </fieldset>

            <small class="text_muted">
                forgot password? <a class="ml-3" href="">reset password</a>
            </small>
        </form>
    </div> 
{% endblock %}

webapp/templates/profile.html
{% extends 'base.html' %}
{% from "_formhelpers.html" import render_field, render_button, render_remember %}


{% block body %}
<div class="container-fluid d-grid my-3">
    <div class="row gap-3">
        <div class="col-md-3 align-self-start shadow">
            <div class="d-flex mx-2 my-4 align-items-center">
                <div class="flex-shrink-0">
                  <img class="rounded-circle" 
                  src="{{url_for('static', filename='profile_images_preview/' + user.profile_image)}}" 
                  alt=""
                  style="width: 100px; height: 100px;"
                  >
                </div>
                <div class="flex-grow-1 ms-3">
                 {{user.username}}  
                </div>
                {% if current_user.is_authenticated %}
                    {% if current_user.id == user.id %}
                        <a aria-current="page" href="{{url_for('account.account_setting')}}">change account</a>  
                    {% else %}
                        {%if current_user.is_following(user) %}
                        <a href="{{ url_for('account.unfollow', user_id=user.id) }}" class="btn btn-outline-primary">unfollow</a>
                        {% else %}
                        <a href="{{ url_for('account.follow', user_id=user.id) }}" class="btn btn-primary">follow</a>
                        {% endif %}
                    {% endif %}
                {% endif %}
            <div>
                
            </div>
        </div>
            


        </div>
        <div class="d-grid col-md-8 gap-3">
            <div class="row-md-3 gap-3 shadow">
                Information
            </div>
            <div class="row-md-3 gap-3 shadow">
                Post
            </div>

        </div>



    </div>
</div>

{% endblock %}

webapp/templates/register.html
{% extends 'base.html' %}
{% from "_formhelpers.html" import render_field, render_button, render_remember %}

{% block body %}
    <div class="container-sm" style="max-width: 600px;">
        <form method="POST" action="">
            {{form.hidden_tag()}}
            <fieldset class="form-group">
                <div class="d-grid gap-1">
                    <legend class="border-bottom me-4">Register</legend>
                    {{render_field(form.email)}}
                    {{render_field(form.username)}}
                    {{render_field(form.password)}}
                    {{render_field(form.confirm_password)}}
                    {{render_button(form.submit)}}
                </div>
            </fieldset>

            <small class="text_muted">
                forgot password? <a class="ml-3" href="">reset password</a>
            </small>
        </form>
    </div> 
{% endblock %}

webapp/templates/user.html
{% extends 'base.html' %}

{% block body %}
{% endblock %}

webapp/templates/user_posts.html
{% extends 'base.html' %}

{% block body %}
<div class="d-grid gap-3 mt-3 ml-3">
    {% for post in posts.items %}
        <div class="p-2 bg-light border shadow">
            <div class="d-flex gap-1">
                <div class="d-flex flex-column align-items-center">
                    <a href="#">
                    <img class="p-0 rounded-circle" 
                    src="{{url_for('static', filename='profile_images_preview/' + post.author.profile_image)}}" 
                    style="width: 75px; height: 75px;">
                    </a>
                    <a class="p-0" href="#">{{ post.author.username }}</a>

                </div>
                <div class="flex-grow-1 vh-10">
                    <h2><a href="{{url_for('post.single_post', post_id = post.id)}}" style="color:inherit; text-decoration: none;">
                         {{post.title}}
                    </a></h2>
                    <p class="border overflow-auto"
                    style="height: 200px;">
                    {{post.text}}
                    </p>
                    {% for image in Image.query.filter_by(post=post) %}
                    <img src="{{url_for('static', filename='images_preview/' + image.image)}}" alt="" width="125px">
                    {% endfor %}
                </div>
            </div>     
        </div>
    {% endfor %}


    <div class="">
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        
        {% if page_num %}
            {% if page_num == posts.page %}
                <a class="btn btn-info mb-4" href="{{url_for('account.user_posts', user_id=user.id, page=page_num)}}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{url_for('account.user_posts', user_id=user.id, page=page_num)}}">{{ page_num }}</a>
            {% endif%} 
        {% else %}
        ...
        {% endif%}
        
        {% endfor %}
    </div>

</div>
{% endblock %}

webapp/templates/users_list.html
{% extends 'base.html' %}
{% from "_formhelpers.html" import render_field, render_button, render_remember %}

{% block body %}
{% for user in users %}
<div>{{user.email}} {{user.username}} {{user.password}}</div>
{% endfor %}
{% endblock %}

webapp/templates/wip.html
<div class="row">
    <div class="col-md-8">
      {% block body %} 
      {% endblock %}
    </div>
    <div class="col-md-3">

      <div class="d-grid gap-3 mt-3 ml-3">
        <div class="d-grid p-2 bg-light border shadow">
          {% if current_user.is_authenticated %}
            <div class="d-flex align-items-top">
              <div class="flex-shrink-0">
                <img class="rounded-circle" 
                src="{{url_for('static', filename='profile_images_preview/' + current_user.profile_image)}}" 
                alt=""
                style="width: 100px; height: 100px;"
                >
              </div>
              <div class="flex-grow-1 ms-3">
               {{current_user.username}}  
              </div>
            </div>
          {% else %}

          <div>work in progress</div>

          {% endif %}

          
        </div>
      </div>

    </div>
  </div>